### ISSUE TITLE
Plugin functionality is gone

### ISSUE THREAD

**Issue by xenDE** [paviliondev/discourse-events#77]
hi,

since some updates/months the map-link in categories and the button for set the location+date of a new post is gone.

what can i check? i dont find something in the logs.

Missing event button:

![grafik](https://user-images.githubusercontent.com/2836430/74926083-9f103380-53d5-11ea-8972-9af792ca6d3f.png)

installed plugin:

![grafik](https://user-images.githubusercontent.com/2836430/74926190-c9fa8780-53d5-11ea-946b-f27994f2c868.png)

it's enabled for all categories:

![grafik](https://user-images.githubusercontent.com/2836430/74926272-ebf40a00-53d5-11ea-8e8a-90b4cdb0b96b.png)

it worked fine some moths ago.

what can i check?

best regards and thanks for this plugin,
daniel

**Comment by fzngagan** [comment]
Can you do these steps
1. disable the plugin and save.
2. Enable it again.
3. Refresh the page.

Does this bring back the functionality

**Comment by xenDE** [comment]
thanks for your fast response.
disable in discourse webconfig on key "events enabled" ?

or in /var/discourse/containers/app.yml remove the "git clone https://github.com/paviliondev/discourse-events" and rebuild?

```
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - mkdir -p plugins
          - git clone https://github.com/paviliondev/discourse-events
```
